name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CI: true

jobs:
  lint:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          check-latest: true
          node-version-file: '.node-version'

      - name: Cache dependencies
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Lint
        run: npm run lint

  test:
    needs: [lint]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          check-latest: true
          node-version-file: '.node-version'

      - name: Cache dependencies
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run jest tests
        run: npm run test

  build:
    needs: [test]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-node@v4
      with:
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
        check-latest: true
        node-version-file: '.node-version'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: ${{ runner.os }}-npm-

    - name: Install dependencies
      run: npm ci --ignore-scripts

    - name: Build
      run: npm run build --if-present

    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: lib-${{ matrix.os }}
        path: lib
        retention-days: 30
