name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CI: true

jobs:
  lint:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 18
          - 20
        architecture:
          - x64
          - x86
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          check-latest: true
          node-version-file: '.node-version'
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}

      - name: Cache dependencies
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ runner.arch }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Lint
        run: npm run lint

  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 18
          - 20
        architecture:
          - x64
          - x86
    needs: [lint]
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: Cache dependencies
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ runner.arch }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run jest tests
        run: npm run test

  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 18
          - 20
        architecture:
          - x64
          - x86
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ runner.arch }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: ${{ runner.os }}-${{ runner.arch }}-npm-

    - name: Install dependencies
      run: npm ci --ignore-scripts

    - name: Build
      run: npm run build --if-present

    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: lib
        path: lib
        retention-days: 30
